version: '3.8'

services:
  backend:
    build: ./backend
    container_name: edutube-backend
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://3.27.0.76:3306/edutube?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=edutube
      - SPRING_DATASOURCE_PASSWORD=edutube
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
